CREATE TABLE brahmastra.fcl_freight_action
(
    id UInt256,
    origin_port_id UUID,
    destination_port_id UUID,
    origin_main_port_id UUID,
    destination_main_port_id UUID,
    origin_region_id UUID,
    destination_region_id UUID,
    origin_country_id UUID,
    destination_country_id UUID,
    origin_continent_id UUID,
    destination_continent_id UUID,
    origin_trade_id UUID,
    destination_trade_id UUID,
    commodity FixedString(256),
    container_size FixedString(256),
    container_type FixedString(256),
    shipping_line_id UUID,
    service_provider_id UUID,
    containers_count UInt8,
    rate_id UUID,
    validity_id UUID,
    bas_price Float64 DEFAULT 0,
    bas_standard_price Float64 DEFAULT 0,
    bas_currency FixedString(3),
    mode FixedString(256),
    parent_mode FixedString(256),
    source FixedString(256),
    source_id UUID,
    standard_price Float64 DEFAULT 0,
    market_price Float64 DEFAULT 0,
    rate_type FixedString(256),
    validity_start DateTime,
    validity_end DateTime,
    currency FixedString(3),
    spot_search_id UUID,
    spot_search UInt8,
    checkout_id UUID,
    checkout UInt8,
    shipment_id UUID,
    shipment UInt8,
    disliked UInt8,
    liked UInt8,
    feedback_id UUID,
    so1_select INT,
    so1_selected_rate_id UUID,
    so1_selected_validity_id UUID,
    source FixedString(256),
    diff_from_selected_so1_rate Float64 DEFAULT 0,
    fcl_freight_rate_statistic_id BIGUInt8,
    selected_fcl_freight_rate_statistic_id BIGUInt8,
    revenue_desk_visit UInt8,
    revenue_desk_select UInt8,
    given_priority UInt8,
    so1_visit UInt8,
    shipment_status FixedString(256),
    cancelled UInt8,
    completed UInt8,
    aborted UInt8,
    confirmed_by_importer_exporter UInt8,
    recieved UInt8,
    status FixedString(256),
    created_at DateTime DEFAULT now(),
    updated_at DateTime DEFAULT now(),
    operation_created_at DateTime,
    operation_updated_at DateTime,
    sign INT DEFAULT 1,
    version INT DEFAULT 1
)
ENGINE = VersionedCollapsingMergeTree(sign, version)
PRIMARY KEY (origin_continent_id, parent_mode,origin_country_id, container_size, origin_port_id, rate_id, id)
ORDER BY (origin_continent_id, parent_mode, origin_country_id, container_size, origin_port_id , rate_id, id, version);