CREATE TABLE brahmastra.fcl_freight_rate_statistics
(
    id UInt256,
    identifier FixedString(256),
    validity_id UUID,
    rate_id UUID,
    payment_term FixedString(256),
    schedule_type FixedString(256),
    origin_port_id UUID,
    destination_port_id UUID,
    origin_main_port_id UUID,
    destination_main_port_id UUID,
    origin_region_id UUID,
    destination_region_id UUID,
    origin_country_id UUID,
    destination_country_id UUID,
    origin_continent_id UUID,
    destination_continent_id UUID,
    origin_trade_id UUID,
    destination_trade_id UUID,
    origin_pricing_zone_map_id UUID,
    destination_pricing_zone_map_id UUID,
    price Float64,    
    standard_price Float64,     
    market_price Float64,
    validity_start Date,
    validity_end Date,
    currency FixedString(3),
    shipping_line_id UUID,
    service_provider_id UUID,
    mode FixedString(256),
    likes_count UInt16 DEFAULT 0,
    dislikes_count UInt16 DEFAULT 0,
    spot_search_count UInt16 DEFAULT 0,
    checkout_count UInt16 DEFAULT 0,
    rate_created_at DateTime DEFAULT now(),
    rate_updated_at DateTime DEFAULT now(),
    validity_created_at DateTime DEFAULT now(),
    validity_updated_at DateTime DEFAULT now(),
    commodity FixedString(256),
    container_size String,
    container_type FixedString(256),
    containers_count UInt8 DEFAULT 0,
    origin_local_id UUID,
    destination_local_id UUID,
    applicable_origin_local_count UInt16 DEFAULT 0,
    applicable_destination_local_count UInt16 DEFAULT 0,
    origin_detention_id UUID,
    destination_detention_id UUID,
    origin_demurrage_id UUID,
    destination_demurrage_id UUID,
    cogo_entity_id UUID,
    rate_type FixedString(256),
    sourced_by_id UUID,
    procured_by_id UUID,
    created_at DateTime DEFAULT now(),
    updated_at DateTime DEFAULT now(),
    version UInt32 DEFAULT 1,
    sign Int8 DEFAULT 1,
    status FixedString(10) DEFAULT 'active',
    last_action FixedString(10) DEFAULT 'create',
    parent_rate_id UUID,
    parent_validity_id UUID,
    so1_select_count UInt16,
    parent_mode FixedString(255),
    source String,
    source_id UUID,
    performed_by_id UUID,
    performed_by_type FixedString(256),
    rate_sheet_id UUID,
    bulk_operation_id UUID,
    operation_created_at DateTime,
    operation_updated_at DateTime,
    is_deleted Bool DEFAULT false,
    bas_price Float64,
    bas_standard_price Float64,
    bas_currency FixedString(3),
    tag FixedString(256),
    shipment_completed UInt16,
    shipment_cancelled UInt16,
    bas_standard_price_accuracy Float64,
    bas_standard_price_diff_from_selected_rate Float64
)
ENGINE = VersionedCollapsingMergeTree(sign, version)
PRIMARY KEY (is_deleted ,origin_continent_id,origin_country_id,origin_port_id,shipping_line_id,rate_id,validity_id)
ORDER BY (is_deleted, origin_continent_id,origin_country_id,origin_port_id,shipping_line_id,rate_id,validity_id, version, id);

CREATE TABLE brahmastra.stale_fcl_freight_rate_statistics
(
    id UInt256,
    identifier FixedString(256),
    validity_id UUID,
    rate_id UUID,
    payment_term FixedString(256),
    schedule_type FixedString(256),
    origin_port_id UUID,
    destination_port_id UUID,
    origin_main_port_id UUID,
    destination_main_port_id UUID,
    origin_region_id UUID,
    destination_region_id UUID,
    origin_country_id UUID,
    destination_country_id UUID,
    origin_continent_id UUID,
    destination_continent_id UUID,
    origin_trade_id UUID,
    destination_trade_id UUID,
    origin_pricing_zone_map_id UUID,
    destination_pricing_zone_map_id UUID,
    price Float64,    
    standard_price Float64,     
    market_price Float64,
    validity_start Date,
    validity_end Date,
    currency FixedString(3),
    shipping_line_id UUID,
    service_provider_id UUID,
    mode FixedString(256),
    likes_count UInt16 DEFAULT 0,
    dislikes_count UInt16 DEFAULT 0,
    spot_search_count UInt16 DEFAULT 0,
    checkout_count UInt16 DEFAULT 0,
    rate_created_at DateTime DEFAULT now(),
    rate_updated_at DateTime DEFAULT now(),
    validity_created_at DateTime DEFAULT now(),
    validity_updated_at DateTime DEFAULT now(),
    commodity FixedString(256),
    container_size String,
    container_type FixedString(256),
    containers_count UInt8 DEFAULT 0,
    origin_local_id UUID,
    destination_local_id UUID,
    applicable_origin_local_count UInt16 DEFAULT 0,
    applicable_destination_local_count UInt16 DEFAULT 0,
    origin_detention_id UUID,
    destination_detention_id UUID,
    origin_demurrage_id UUID,
    destination_demurrage_id UUID,
    cogo_entity_id UUID,
    rate_type FixedString(256),
    sourced_by_id UUID,
    procured_by_id UUID,
    created_at DateTime DEFAULT now(),
    updated_at DateTime DEFAULT now(),
    version UInt32 DEFAULT 1,
    sign Int8 DEFAULT 1,
    status FixedString(10) DEFAULT 'active',
    last_action FixedString(10) DEFAULT 'create',
    parent_rate_id UUID,
    parent_validity_id UUID,
    so1_select_count UInt16,
    parent_mode FixedString(255),
    source String,
    source_id UUID,
    performed_by_id UUID,
    performed_by_type FixedString(256),
    rate_sheet_id UUID,
    bulk_operation_id UUID,
    operation_created_at DateTime,
    operation_updated_at DateTime,
    is_deleted Bool DEFAULT false,
    bas_price Float64,
    bas_standard_price Float64,
    bas_currency FixedString(3),
    tag FixedString(256),
    shipment_completed UInt16,
    shipment_cancelled UInt16,
    bas_standard_price_accuracy Float64,
    bas_standard_price_diff_from_selected_rate Float64
)
ENGINE = VersionedCollapsingMergeTree(sign, version)
PRIMARY KEY (is_deleted ,origin_continent_id,origin_country_id,origin_port_id,shipping_line_id,rate_id,validity_id)
ORDER BY (is_deleted, origin_continent_id,origin_country_id,origin_port_id,shipping_line_id,rate_id,validity_id,version,id);