CREATE TABLE brahmastra.spot_search_fcl_freight_rate_statistics
(
    id UInt256,
    origin_port_id UUID,
    destination_port_id UUID,
    origin_main_port_id UUID,
    destination_main_port_id UUID,
    origin_region_id UUID,
    destination_region_id UUID,
    origin_country_id UUID,
    destination_country_id UUID,
    origin_continent_id UUID,
    destination_continent_id UUID,
    commodity String,
    container_size FixedString(256),
    container_type String,
    spot_search_id UUID,
    checkout_id UUID,
    checkout Int8,
    shipment_id UUID,
    shipment UInt8,
    importer_exporter_id UUID,
    number_of_rates_shown UInt8,
    number_of_rates_disliked UInt8,
    number_of_rates_liked UInt8,
    rate_requested UInt8,
    rate_requested_ids Array(UUID),
    feedback_ids Array(UUID),
    fcl_freight_rate_statistic_id UInt256,
    selected_fcl_freight_rate_statistic_id UInt256,
    standard_diff_from_selected_rate Float32,
    revenue_desk_visit UInt8,
    so1_visit UInt8,
    cancelled UInt8,
    completed UInt8,
    aborted UInt8,
    confirmed_by_importer_exporter UInt8,
    operation_created_at DateTime,
    operation_updated_at DateTime,
    created_at DateTime DEFAULT now(),
    updated_at DateTime DEFAULT now(),
    version UInt32,
    sign Int8
)
ENGINE = VersionedCollapsingMergeTree(sign, version)
PRIMARY KEY (origin_continent_id, origin_country_id, container_size, commodity)
ORDER BY (origin_continent_id, origin_country_id, container_size, commodity, standard_diff_from_selected_rate,version);