CREATE TABLE brahmastra.shipment_fcl_freight_rate_services_statistics
(
    id UInt256,
    shipment_id UUID,
    shipment_fcl_freight_service_id UUID,
    service_state UUID,
    service_is_active Bool,
    service_cancellation_reason String,
    service_created_at DateTime DEFAULT now(),
    service_updated_at DateTime DEFAULT now(),
    shipping_line_id UUID,
    service_provider_id UUID,
    serial_id UInt256,
    importer_exporter_id UUID,
    shipment_type FixedString(256),
    services Array(FixedString(256)),
    source FixedString(256),
    source_id UUID,
    state FixedString(256),
    cancellation_reason String,
    sell_quotation_id UUID,
    total_price Float32,
    total_price_discounted Float32,
    tax_price Float32,
    tax_price_discounted Float32,
    tax_total_price Float32,
    tax_total_price_discounted Float32,
    currency FixedString(3),
    standard_total_price Float32,
    created_at DateTime DEFAULT now(),
    updated_at DateTime DEFAULT now(),
    status FixedString(10) DEFAULT 'active',
    sign Int8 DEFAULT 1,
    version UInt32 DEFAULT 1
)
ENGINE = VersionedCollapsingMergeTree(sign, version)
PRIMARY KEY (rate_id)
ORDER BY (rate_id,id);


CREATE TABLE brahmastra.shipment_fcl_freight_rate_services_statistics
(
    id UInt256,
    shipment_id UUID,
    shipment_fcl_freight_service_id UUID,
    service_state UUID,
    service_is_active Bool,
    service_cancellation_reason String,
    service_created_at DateTime DEFAULT now(),
    service_updated_at DateTime DEFAULT now(),
    shipping_line_id UUID,
    service_provider_id UUID,
    serial_id UInt256,
    importer_exporter_id UUID,
    shipment_type FixedString(256),
    services Array(FixedString(256)),
    source FixedString(256),
    source_id UUID,
    state FixedString(256),
    cancellation_reason String,
    sell_quotation_id UUID,
    total_price Float32,
    total_price_discounted Float32,
    tax_price Float32,
    tax_price_discounted Float32,
    tax_total_price Float32,
    tax_total_price_discounted Float32,
    currency FixedString(3),
    standard_total_price Float32,
    created_at DateTime DEFAULT now(),
    updated_at DateTime DEFAULT now(),
    status FixedString(10) DEFAULT 'active',
    sign Int8 DEFAULT 1,
    version UInt32 DEFAULT 1
)
ENGINE = file(CSV);