CREATE TABLE brahmastra.air_freight_rate_statistics
(
    id UInt256,
    identifier FixedString(256),
    validity_id UUID,
    rate_id UUID,
    origin_airport_id UUID,
    destination_airport_id UUID,
    origin_country_id UUID,
    destination_country_id UUID,
    origin_continent_id UUID,
    destination_continent_id UUID,
    origin_region_id UUID,
    destination_region_id UUID,
    origin_trade_id UUID DEFAULT NULL,
    destination_trade_id UUID DEFAULT NULL,
    origin_pricing_zone_map_id UUID DEFAULT NULL,
    destination_pricing_zone_map_id UUID DEFAULT NULL,
    price Float64,
    lower_limit Float64,
    upper_limit Float64,
    currency FixedString(3),
    validity_start Date,
    validity_end Date,
    density_category FixedString(256),
    max_density_weight Float64,
    min_density_weight Float64,
    airline_id UUID DEFAULT NULL,
    service_provider_id UUID DEFAULT NULL,
    accuracy Float64 DEFAULT -1.0,
    source FixedString(256),
    likes_count UInt16 DEFAULT 0,
    dislikes_count UInt16 DEFAULT 0,
    spot_search_count UInt16 DEFAULT 0,
    buy_quotations_created UInt16 DEFAULT 0,
    sell_quotations_created UInt16 DEFAULT 0,
    checkout_count UInt16 DEFAULT 0,
    bookings_created UInt16 DEFAULT 0,
    rate_created_at DateTime DEFAULT now(),
    rate_updated_at DateTime DEFAULT now(),
    validity_created_at DateTime DEFAULT now(),
    validity_updated_at DateTime DEFAULT now(),
    commodity FixedString(256) DEFAULT NULL,
    commodity_type FixedString(256) DEFAULT NULL,
    commodity_sub_type FixedString(256) DEFAULT NULL,
    operation_type FixedString(256) DEFAULT NULL,
    shipment_type FixedString(256) DEFAULT NULL,
    stacking_type FixedString(256) DEFAULT NULL,
    origin_local_id UUID DEFAULT NULL,
    destination_local_id UUID DEFAULT NULL,
    surcharge_id UUID DEFAULT NULL,
    cogo_entity_id UUID DEFAULT NULL,
    price_type FixedString(256) DEFAULT NULL,
    rate_type FixedString(256),
    sourced_by_id UUID DEFAULT NULL,
    procured_by_id UUID DEFAULT NULL,
    shipment_aborted_count UInt16 DEFAULT 0,
    shipment_cancelled_count UInt16 DEFAULT 0,
    shipment_completed_count UInt16 DEFAULT 0,
    shipment_confirmed_by_service_provider_count UInt16 DEFAULT 0,
    shipment_awaited_service_provider_confirmation_count UInt16 DEFAULT 0,
    shipment_init_count UInt16 DEFAULT 0,
    shipment_flight_arrived_count UInt16 DEFAULT 0,
    shipment_flight_departed_count UInt16 DEFAULT 0,
    shipment_cargo_handed_over_at_destination_count UInt16 DEFAULT 0,
    shipment_is_active_count UInt16 DEFAULT 0,
    created_at DateTime DEFAULT now(),
    updated_at DateTime DEFAULT now(),
    version UInt32 DEFAULT 1,
    sign Int8 DEFAULT 1,
    status FixedString(10) DEFAULT 'active',
    last_action FixedString(10) DEFAULT 'create',
    rate_deviation_from_booking_rate Float32 DEFAULT 0,
    rate_deviation_from_booking_on_cluster_base_rate Float32 DEFAULT 0,
    rate_deviation_from_latest_booking Float32 DEFAULT 0,
    average_booking_rate Float64 DEFAULT -1
)
ENGINE = File(CSV);