import os
from dotenv import load_dotenv
load_dotenv()

# ENV
APP_ENV=os.getenv("APP_ENV")

# Main DB connection
DATABASE_NAME = os.getenv("DATABASE_NAME")
DATABASE_USER = os.getenv("DATABASE_USER")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
DATABASE_HOST = os.getenv("DATABASE_HOST")
DATABASE_PORT = os.getenv("DATABASE_PORT")

# RAILS DB connection

RAILS_DATABASE_NAME = os.getenv("RAILS_DATABASE_NAME")
RAILS_DATABASE_USER = os.getenv("RAILS_DATABASE_USER")
RAILS_DATABASE_PASSWORD = os.getenv("RAILS_DATABASE_PASSWORD")
RAILS_DATABASE_HOST = os.getenv("RAILS_DATABASE_HOST")
RAILS_DATABASE_PORT = os.getenv("RAILS_DATABASE_PORT")

# microservice
RUBY_ADDRESS_URL=os.getenv("RUBY_ADDRESS_URL")
RUBY_AUTHTOKEN = os.getenv('RUBY_AUTHTOKEN')
RUBY_AUTHSCOPE = os.getenv('RUBY_AUTHSCOPE')
RUBY_AUTHSCOPEID = os.getenv('RUBY_AUTHSCOPEID')


MICRO_SERVICE_NAMESPACE=os.getenv("MICRO_SERVICE_NAMESPACE")
COMMON_SERVICE_PORT=os.getenv("COMMON_SERVICE_PORT")
COMMON_SERVICE_NAME=os.getenv("COMMON_SERVICE_NAME")
AUTH_SERVICE_NAME=os.getenv("AUTH_SERVICE_NAME")
AUTH_SERVICE_PORT=os.getenv("AUTH_SERVICE_PORT")
COGOMAPS_SERVICE_NAME =os.getenv("COGOMAPS_SERVICE_NAME")
COGOMAPS_SERVICE_PORT =os.getenv("COGOMAPS_SERVICE_PORT")
INTERNAL_NLB=os.getenv("INTERNAL_NLB")

# Redis
REDIS_HOST=os.getenv("REDIS_HOST")
REDIS_PORT=os.getenv("REDIS_PORT")
REDIS_USERNAME=os.getenv("REDIS_USERNAME")
REDIS_PASSWORD=os.getenv("REDIS_PASSWORD")

# aws
SHARE_POINT_SITE = os.getenv("SHARE_POINT_SITE")
SHARE_POINT_USER = os.getenv("SHARE_POINT_USER")
SHARE_POINT_PASSWORD = os.getenv("SHARE_POINT_PASSWORD")
AWS_S3_BUCKET_NAME = os.getenv("AWS_S3_BUCKET_NAME")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_S3_REGION_NAME = "ap-south-1"
