from peewee import *
from playhouse.postgres_ext import *
from database.db_session import db_rails

class BaseModel(Model):
    class Meta:
        database = db_rails

class Organization(BaseModel):
    about = CharField(null=True)
    account_type = CharField(null=True)
    agent_id = UUIDField(null=True)
    air_freight_destination_location_ids = ArrayField(constraints=[SQL("DEFAULT '{}'::uuid[]")], field_class=UUIDField, index=True, null=True)
    air_freight_destination_port_ids = ArrayField(constraints=[SQL("DEFAULT '{}'::uuid[]")], field_class=UUIDField, null=True)
    air_freight_estimated_volume = CharField(index=True, null=True)
    air_freight_months = ArrayField(constraints=[SQL("DEFAULT '{}'::character varying[]")], field_class=CharField, index=True, null=True)
    air_freight_origin_location_ids = ArrayField(constraints=[SQL("DEFAULT '{}'::uuid[]")], field_class=UUIDField, index=True, null=True)
    air_freight_origin_port_ids = ArrayField(constraints=[SQL("DEFAULT '{}'::uuid[]")], field_class=UUIDField, null=True)
    air_freight_volume = IntegerField(index=True, null=True)
    auto_quotation_subscribed = BooleanField(null=True)
    booking_agent_preference = CharField(index=True, null=True)
    bookings_completed_count = IntegerField(null=True)
    bookings_completed_last_date = DateField(null=True)
    bookings_count = IntegerField(constraints=[SQL("DEFAULT 0")], null=True)
    bookings_last_date = DateField(index=True, null=True)
    bookings_services = ArrayField(constraints=[SQL("DEFAULT '{}'::character varying[]")], field_class=CharField, index=True, null=True)
    business_name = CharField(null=True)
    category_types = ArrayField(field_class=CharField, null=True)
    city_id = UUIDField(null=True)
    ckam_id = UUIDField(null=True)
    cogo_entity_id = UUIDField(null=True)
    comment = CharField(null=True)
    commodities = ArrayField(constraints=[SQL("DEFAULT '{}'::character varying[]")], field_class=CharField, index=True, null=True)
    company_size = CharField(index=True, null=True)
    company_type = CharField(null=True)
    container_subscriptions_count = IntegerField(null=True)
    container_subscriptions_last_date = DateField(index=True, null=True)
    country_id = UUIDField(null=True)
    created_at = DateTimeField()
    credit_days_requested = IntegerField(null=True)
    credit_limit_currency = CharField(null=True)
    credit_limit_requested = DoubleField(null=True)
    default_booking_agent_id = UUIDField(null=True)
    demo_status = CharField(constraints=[SQL("DEFAULT 'pending'::character varying")], null=True)
    employee_count = CharField(index=True, null=True)
    enquiries_count = IntegerField(null=True)
    enquiries_last_date = DateField(null=True)
    except_agent_ids = ArrayField(constraints=[SQL("DEFAULT '{}'::uuid[]")], field_class=UUIDField, null=True)
    exchange_rate_preference = BinaryJSONField(null=True)
    fcl_freight_containers_count = IntegerField(index=True, null=True)
    fcl_freight_destination_location_ids = ArrayField(constraints=[SQL("DEFAULT '{}'::uuid[]")], field_class=UUIDField, index=True, null=True)
    fcl_freight_destination_port_ids = ArrayField(constraints=[SQL("DEFAULT '{}'::uuid[]")], field_class=UUIDField, null=True)
    fcl_freight_estimated_volume = CharField(index=True, null=True)
    fcl_freight_months = ArrayField(constraints=[SQL("DEFAULT '{}'::character varying[]")], field_class=CharField, index=True, null=True)
    fcl_freight_origin_location_ids = ArrayField(constraints=[SQL("DEFAULT '{}'::uuid[]")], field_class=UUIDField, index=True, null=True)
    fcl_freight_origin_port_ids = ArrayField(constraints=[SQL("DEFAULT '{}'::uuid[]")], field_class=UUIDField, null=True)
    features_preference = ArrayField(constraints=[SQL("DEFAULT '{}'::character varying[]")], field_class=CharField, null=True)
    freight_rates_added = BooleanField(null=True)
    id = UUIDField(constraints=[SQL("DEFAULT gen_random_uuid()")], primary_key=True)
    import_export_experience = CharField(index=True, null=True)
    import_export_types = ArrayField(constraints=[SQL("DEFAULT '{}'::character varying[]")], field_class=CharField, index=True, null=True)
    industries = ArrayField(constraints=[SQL("DEFAULT '{}'::character varying[]")], field_class=CharField, index=True, null=True)
    is_contract_created = BooleanField(constraints=[SQL("DEFAULT false")], null=True)
    is_tax_applicable = BooleanField(null=True)
    kyc_rejection_reason = CharField(null=True)
    kyc_status = CharField(constraints=[SQL("DEFAULT 'pending_from_user'::character varying")], null=True)
    kyc_submitted_from = CharField(null=True)
    kyc_verified_at = DateTimeField(null=True)
    lcl_freight_destination_location_ids = ArrayField(constraints=[SQL("DEFAULT '{}'::uuid[]")], field_class=UUIDField, index=True, null=True)
    lcl_freight_destination_port_ids = ArrayField(constraints=[SQL("DEFAULT '{}'::uuid[]")], field_class=UUIDField, null=True)
    lcl_freight_estimated_volume = CharField(index=True, null=True)
    lcl_freight_months = ArrayField(constraints=[SQL("DEFAULT '{}'::character varying[]")], field_class=CharField, index=True, null=True)
    lcl_freight_origin_location_ids = ArrayField(constraints=[SQL("DEFAULT '{}'::uuid[]")], field_class=UUIDField, index=True, null=True)
    lcl_freight_origin_port_ids = ArrayField(constraints=[SQL("DEFAULT '{}'::uuid[]")], field_class=UUIDField, null=True)
    lcl_freight_volume = IntegerField(index=True, null=True)
    lead_organization_id = UUIDField(null=True)
    logistics_modes = ArrayField(constraints=[SQL("DEFAULT '{}'::character varying[]")], field_class=CharField, index=True, null=True)
    logistics_services = ArrayField(constraints=[SQL("DEFAULT '{}'::character varying[]")], field_class=CharField, null=True)
    logo = CharField(null=True)
    only_agent_ids = ArrayField(constraints=[SQL("DEFAULT '{}'::uuid[]")], field_class=UUIDField, null=True)
    partner_id = UUIDField(null=True)
    pincode_id = UUIDField(null=True)
    preferred_languages = ArrayField(constraints=[SQL("DEFAULT '{}'::character varying[]")], field_class=CharField, null=True)
    preferred_products = ArrayField(constraints=[SQL("DEFAULT '{}'::character varying[]")], field_class=CharField, null=True)
    query_name = CharField(index=True, null=True)
    quotations_count = IntegerField(null=True)
    quotations_last_date = DateField(null=True)
    region_id = UUIDField(null=True)
    registration_number = CharField(index=True, null=True)
    sage_company_id = CharField(index=True, null=True)
    search_rating = IntegerField(constraints=[SQL("DEFAULT 0")], null=True)
    serial_id = BigIntegerField(constraints=[SQL("DEFAULT nextval('organizations_serial_id_seq'::regclass)")], index=True)
    short_name = CharField(null=True)
    skippable_checks = ArrayField(field_class=CharField, null=True)
    spot_negotiation_rates_count = IntegerField(null=True)
    spot_negotiation_rates_last_date = DateField(null=True)
    spot_searches_count = IntegerField(null=True)
    spot_searches_last_date = DateField(index=True, null=True)
    spot_searches_services = ArrayField(constraints=[SQL("DEFAULT '{}'::character varying[]")], field_class=CharField, null=True)
    status = CharField(constraints=[SQL("DEFAULT 'active'::character varying")], null=True)
    tags = ArrayField(constraints=[SQL("DEFAULT '{}'::character varying[]")], field_class=CharField, index=True, null=True)
    tds_certificate_end_date = DateField(null=True)
    tds_certificate_number = CharField(null=True)
    tds_certificate_start_date = DateField(null=True)
    tds_deduction_limit = IntegerField(null=True)
    tds_deduction_rate = DoubleField(null=True)
    tds_deduction_style = CharField(null=True)
    tds_deduction_type = CharField(null=True)
    total_freight_estimated_volume = CharField(null=True)
    trade_bodies = ArrayField(constraints=[SQL("DEFAULT '{}'::character varying[]")], field_class=CharField, null=True)
    trade_contacts_count = IntegerField(null=True)
    trade_contacts_last_date = DateField(null=True)
    trade_country_ids = ArrayField(constraints=[SQL("DEFAULT '{}'::uuid[]")], field_class=UUIDField, null=True)
    trade_documents_count = IntegerField(null=True)
    trade_documents_last_date = DateField(null=True)
    trade_name = CharField(null=True)
    updated_at = DateTimeField()
    utility_bill_document_url = CharField(null=True)
    website = CharField(null=True)
    welcome_email_sent_at = DateTimeField(null=True)

    class Meta:
        table_name = 'organizations'
        indexes = (
            (('account_type', 'kyc_status'), False),
            (('account_type', 'status', 'kyc_status'), False),
            (('partner_id', 'agent_id'), False),
            (('status', 'kyc_status'), False),
        )