CREATE DATABASE IF NOT EXISTS brahmastra;

CREATE TABLE brahmastra.fcl_freight_rate_statistics
(
    id UInt128,
    identifier UUID,
    validity_id UUID,
    rate_id UUID,
    origin_port_id UUID,
    destination_port_id UUID,
    origin_main_port_id UUID,
    destination_main_port_id UUID,
    origin_country_id UUID,
    destination_country_id UUID,
    origin_continent_id UUID,
    destination_continent_id UUID,
    origin_trade_id UUID,
    destination_trade_id UUID,
    origin_pricing_zone_map_id UUID,
    destination_pricing_zone_map_id UUID,
    shipping_line_id UUID,
    service_provider_id UUID,
    price Float32,
    currency FixedString(3),
    accuracy Float32,
    mode FixedString(256),
    likes_count UInt64,
    dislikes_count UInt64,
    spot_search_count UInt64,
    quotations_created UInt64,
    checkout_count UInt64,
    bookings_created UInt64,
    rate_created_at DateTime('Etc/UTC'),
    rate_updated_at DateTime('Etc/UTC'),
    validity_created_at DateTime('Etc/UTC'),
    validity_updated_at DateTime('Etc/UTC'),
    commodity FixedString(256),
    container_size FixedString(256),
    container_type FixedString(256),
    containers_count UInt8,
    origin_local_id UUID,
    destination_local_id UUID,
    applicable_origin_local_count UInt64,
    applicable_destination_local_count UInt64,
    origin_detention_id UUID,
    destination_detention_id UUID,
    origin_demurrage_id UUID,
    destintination_demurrage_id UUID,
    cogo_entity_id UUID,
    rate_type FixedString(256),
    tags Array(FixedString(256)),
    free_limit UInt8,
    sourced_by_id UUID,
    spot_search_to_checkout_count UInt8,
    checkout_to_quotation_count UInt8,
    quotation_to_shipment_count UInt8,
    procured_by_id UUID,
    shipment_aborted_count UInt8,
    shipment_cancelled_count UInt8,
    shipment_completed_count UInt8,
    shipment_confirmed_by_service_provider_countb UInt8,
    shipment_awaited_service_provider_confirmation_count UInt8,
    shipment_init_count UInt8,
    shipment_containers_gated_in_count UInt8,
    shipment_containers_gated_out_count UInt8,
    shipment_vessel_arrived_count UInt8,
    shipment_is_active_count UInt8,
    shipment_cancellation_reason_got_a_cheaper_rate_from_my_service_provider_count UInt8,
    shipment_booking_rate_is_too_low_count UUID,
    rate_deviation Float32,
    created_at DateTime DEFAULT now(),
    updated_at DateTime DEFAULT now(),
    version Int8
)
ENGINE = MergeTree()
PRIMARY KEY (origin_continent_id,destination_continent_id,origin_country_id,destination_country_id,origin_region_id,destination_region_id,origin_main_port_id,destination_main_port_id,origin_port_id,destination_port_id,rate_id,validity_id)
ORDER BY (origin_continent_id,destination_continent_id,origin_country_id,destination_country_id,origin_region_id,destination_region_id,origin_main_port_id,destination_main_port_id,origin_port_id,destination_port_id,rate_id,validity_id,rate_deviation,updated_at);